Bugfix/teamred 51
sasa-bonta/WebShop_preot.md pull request #12
Opened 2021-05-28 18:59 UTC by sasa-bonta

2021-05-28 19:21 UTC, aharabara requested changes

2021-05-28 19:21 UTC, aharabara commented on README.md
> +- (optional) composer require --dev symfony/profiler-pack
все зависимости, которые есть в composer.json будуз запрошены при выполнении `composer install`, нет нужды их запрашивать отдельно

2021-05-28 19:21 UTC, aharabara commented on public/assets/main/navbar/admin/gallery.js
> +    if (window.location.origin + window.location.pathname !== "http://localhost:8000/admin/gallery/") {
абсолютный url. если я запущу это на своей машине, но с другим хостом, то ваш код перестанет работать

2021-05-28 19:21 UTC, aharabara commented on public/assets/main/navbar/admin/users.js
> +if (urlParams.has("limit")) {
Не уверен, но помоему этот код несколько раз повторяется. Может стоит вытащить всё в группу функций или класс, чтобы можно было переиспользовать поиск?

2021-05-28 19:21 UTC, aharabara commented on src/Controller/ImageController.php
> +            $this->deleteImageFromProducts($image, $productRepository);
Почему delete делается и в репозитории и в контроллере?

2021-05-28 19:21 UTC, aharabara commented on src/Controller/ProductApiController.php
> +            throw new BadRequestHttpException("Nonexistent column name");
Может быть перенесено внутрь SearchCriteria, потому что по сути является частью логики этого класса

2021-05-28 19:21 UTC, aharabara commented on src/Controller/ProductApiController.php
> +        $keys = ['code', 'name', 'category', 'price', 'availableAmount', 'description'];
`required => true` ?

2021-05-28 19:21 UTC, aharabara commented on src/Controller/ProductApiController.php
>          $keys = ['code', 'name', 'category', 'price', 'availableAmount', 'description'];
почему не добавить соответствующие проверки в форме?

2021-05-28 19:21 UTC, aharabara commented on src/Security/TokenAuthenticator.php
> +        return $request->headers->has('X-AUTH-TOKEN');
если я не укажу хэдэр, то пройду мимо, без необходимости указывать токен. Лучше просто возвращать сразу true, но при условии что у тебя больше нет аутентикейторов на одном и том же фаерволе

2021-05-28 19:21 UTC, aharabara commented on src/Security/TokenAuthenticator.php
> +        return $request->headers->get('X-AUTH-TOKEN');
если не указать хэдэр, но в суппорте возвращать true, то тут будет ошибка, так что лучше добавить `?? ''`

2021-05-28 19:21 UTC, aharabara commented on src/Service/CheckUserService.php
> +        $this->errors = [];
сервисы не должны сохранять состояние данных, иначе если кто-то будет использовать твой код не так, как ты задумал, то можно получить непредвиденное поведение. Самый адекватный вариант - создавать состояние только на период отработки функции. Советую тебе отказаться от `this->errors` и использовать просто `$errors`

2021-05-28 19:21 UTC, aharabara commented on templates/base.html.twig
>      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
jquery дважды грузится, надо один убрать. Можно все js скрипты перенести пере закрывающим тэгом body

2021-05-29 08:18 UTC, sasa-bonta commented on README.md
> +- (optional) composer require --dev symfony/profiler-pack
Сделал

2021-05-29 17:40 UTC, sasa-bonta commented on src/Controller/ImageController.php
> +            $this->deleteImageFromProducts($image, $productRepository);
Функция deleteImageFromProducts удаляет картинку из всех продуктов, в которых она есть.  $filesystem->remove($gallery . $image->getPath()) удаляет картинку из файлов.  $entityManager->remove($image); удаляет запись про картинку из юазы данных

2021-05-29 17:41 UTC, sasa-bonta commented on src/Controller/ProductApiController.php
> +            throw new BadRequestHttpException("Nonexistent column name");
В Search Criteria сделал наследство. Про api забыл. Исправил

2021-05-29 17:41 UTC, sasa-bonta commented on src/Controller/ProductApiController.php
>          $keys = ['code', 'name', 'category', 'price', 'availableAmount', 'description'];
Сделано

2021-05-29 17:41 UTC, sasa-bonta commented on src/Security/TokenAuthenticator.php
> +        return $request->headers->has('X-AUTH-TOKEN');
Сделал как ты показал

2021-05-29 17:42 UTC, sasa-bonta commented on src/Security/TokenAuthenticator.php
> +        return $request->headers->get('X-AUTH-TOKEN');
Сделал как ты показал

2021-05-29 17:44 UTC, sasa-bonta commented on templates/base.html.twig
>      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
Тут вроде ajax и jQuery?

2021-05-29 19:04 UTC, sasa-bonta commented on public/assets/main/navbar/admin/gallery.js
> +    if (window.location.origin + window.location.pathname !== "http://localhost:8000/admin/gallery/") {
Fixed. 
 var inputVal = document.getElementById("myInput").value;
    var urlSearchParams;
    if ($('body').data('route-name').indexOf('user_index') !== 0) {
        urlSearchParams = new URL(document.location.protocol + "//" + document.location.host + "/admin/users/");
        urlSearchParams.searchParams.set("name", inputVal);
        urlSearchParams.searchParams.set("page", 1);
        window.location.replace(urlSearchParams);
    } else {
        urlSearchParams = new URLSearchParams(window.location.search);
        urlSearchParams.set("name", inputVal);
        urlSearchParams.set("page", 1);
        window.location.search = urlSearchParams;
    }

2021-05-29 19:15 UTC, sasa-bonta commented on public/assets/main/navbar/admin/users.js
> +if (urlParams.has("limit")) {
Че-то не очень получается. ПОка что оставлю так

2021-05-31 05:54 UTC, sasa-bonta commented on src/Service/CheckUserService.php
> +        $this->errors = [];
Переделал

2021-05-31 14:38 UTC, aharabara commented on src/Controller/ImageController.php
> +            $this->deleteImageFromProducts($image, $productRepository);
вот такие кусочки кода и надо выводить в сервисы, чтобы они работали как одна транзакция. (*необязательно)

2021-05-31 14:47 UTC, aharabara approved these changes

2021-05-31 14:47 UTC, aharabara commented on src/Service/CheckUserService.php
> +    private function checkUsername(User $newUser, User $origUser = null)
лучше уж сделать чтобы djpdhfofkj `bool`, чем `?string`. Смог бы написать что-то формата
```
if ($this->checkUsername($newUser, $origUser)) {
    $errors['nick'] = ""This nickname already exists";
}
```
вместо того, что у тебя есть

2021-05-31 14:47 UTC, aharabara commented on src/Service/CheckUserService.php
> +    private function checkUsername(User $newUser, User $origUser = null)
*необязательно, потом поправишь

2021-05-31 14:47 UTC, aharabara commented on src/DataFixtures/UserFixtures.php
> +        $uuid = Uuid::uuid6();
ненужная линия. * потом поправишь

2021-05-31 14:47 UTC, aharabara commented on src/Controller/ProductApiController.php
>          $keys = ['code', 'name', 'category', 'price', 'availableAmount', 'description'];
Но ведь foreach остался?

2021-05-31 14:49 UTC, sasa-bonta commented on src/Controller/ProductApiController.php
>          $keys = ['code', 'name', 'category', 'price', 'availableAmount', 'description'];
Уже убрал

2021-05-31 15:07 UTC, merged